// PIMProbe - touch probing for the Nestworks C500.
// Copyright (c) 2026 Konstantin Tcepliaev <f355@f355.org>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const docs = new URL("../docs/", import.meta.url);
const pageNames = ["outside", "inside", "center", "settings"];

// Standalone page links expand into their contents in contextual help.
export function renderPage(name, parents = [], source = docs) {
    if (parents.includes(name)) throw new Error("Circular help link: " + name);
    return readFileSync(new URL(name, source), "utf8")
        .replace(/^# [^\n]+\n+/, "")
        .replace(/<!-- guide-only -->[\s\S]*?<!-- \/guide-only -->/g, "")
        .replace(/^\[([^\]]+)\]\(([a-z-]+\.md)\)$/gm,
            (_, label, target) => renderPage(target, [...parents, name], source).trim());
}

export function compileHelp() {
    const pages = pageNames.map(name => renderPage(name + ".md"));
    const notice = readFileSync(new URL("license-header.txt", import.meta.url), "utf8").trimEnd()
        .split("\n").map(line => line ? "// " + line : "//").join("\n") + "\n\n";
    return notice + "// Generated by node dev/build-help.mjs from docs/*.md.\n.pragma library\n\nvar pages = " +
        JSON.stringify(pages, null, 4) + ";\n";
}

export function buildHelp(ui = new URL("../ui/", import.meta.url)) {
    const bundle = compileHelp();
    const help = new URL("help/", ui);
    const assets = new Set(pageNames.flatMap(name =>
        [...renderPage(name + ".md").matchAll(/!\[[^\]]*\]\((images\/[^)]+)\)/g)].map(match => match[1])));
    for (const asset of assets) {
        const target = new URL(asset, help);
        mkdirSync(new URL(".", target), { recursive: true });
        copyFileSync(new URL(asset, docs), target);
    }
    writeFileSync(new URL("HelpPages.js", ui), bundle);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) buildHelp();
